name: Build APK

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest # You can choose a different runner if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.5' # Adjust to your Flutter version

      - name: Build APK
        run: flutter build apk
